\echo '******** Set The Database ********'

\c db_psi

\echo '********* Inserting some data *********'

\echo '********* Restarting all sequences *********'
ALTER SEQUENCE adimages_id_seq RESTART;
ALTER SEQUENCE ads_id_seq RESTART;
ALTER SEQUENCE clients_id_seq RESTART;
ALTER SEQUENCE categories_id_seq RESTART;
ALTER SEQUENCE messages_id_seq RESTART;

\echo '********* Inserting some categories *********'
INSERT INTO categories (name) VALUES ('informatique');
INSERT INTO categories (name) VALUES ('Consoles & Jeux vidéo');
INSERT INTO categories (name) VALUES ('Image & Son');
INSERT INTO categories (name) VALUES ('Téléphonie');
INSERT INTO categories (name) VALUES ('Ameublement');
INSERT INTO categories (name) VALUES ('Électroménager');
INSERT INTO categories (name) VALUES ('Arts de la table');
INSERT INTO categories (name) VALUES ('Décoration');
INSERT INTO categories (name) VALUES ('Linge de maison');
INSERT INTO categories (name) VALUES ('Bricolage');
INSERT INTO categories (name) VALUES ('Jardinage');
INSERT INTO categories (name) VALUES ('Vêtements');
INSERT INTO categories (name) VALUES ('Chaussures');
INSERT INTO categories (name) VALUES ('Accessoires & Bagagerie');
INSERT INTO categories (name) VALUES ('Montres & Bijoux');
INSERT INTO categories (name) VALUES ('Équipement bébé');
INSERT INTO categories (name) VALUES ('Vêtements bébé');
INSERT INTO categories (name) VALUES ('Luxe et Tendance');
INSERT INTO categories (name) VALUES ('Locations & Gîtes');
INSERT INTO categories (name) VALUES ('Chambres de hôtes');
INSERT INTO categories (name) VALUES ('Campings');
INSERT INTO categories (name) VALUES ('Hôtels');
INSERT INTO categories (name) VALUES ('Hébergements insolites');
INSERT INTO categories (name) VALUES ('Ventes privées vacances');
INSERT INTO categories (name) VALUES ('Voitures');
INSERT INTO categories (name) VALUES ('Motos');
INSERT INTO categories (name) VALUES ('Caravaning');
INSERT INTO categories (name) VALUES ('Utilitaires');
INSERT INTO categories (name) VALUES ('Camions');
INSERT INTO categories (name) VALUES ('Nautisme');
INSERT INTO categories (name) VALUES ('Équipement auto');
INSERT INTO categories (name) VALUES ('Équipement moto');
INSERT INTO categories (name) VALUES ('Équipement caravaning');
INSERT INTO categories (name) VALUES ('Équipement nautisme');
INSERT INTO categories (name) VALUES ('Ventes immobilières');
INSERT INTO categories (name) VALUES ('Immobilier Neuf');
INSERT INTO categories (name) VALUES ('Locations');
INSERT INTO categories (name) VALUES ('Colocations');
INSERT INTO categories (name) VALUES ('Bureaux & Commerces');
INSERT INTO categories (name) VALUES ('Animaux');
INSERT INTO categories (name) VALUES ('DVD - Films');
INSERT INTO categories (name) VALUES ('CD - Musique');
INSERT INTO categories (name) VALUES ('Livres');
INSERT INTO categories (name) VALUES ('Vélos');
INSERT INTO categories (name) VALUES ('Sports & Hobbies');
INSERT INTO categories (name) VALUES ('Instruments de musique');
INSERT INTO categories (name) VALUES ('Collection');
INSERT INTO categories (name) VALUES ('Jeux & Jouets');
INSERT INTO categories (name) VALUES ('Vins & Gastronomie');
\echo '********* Inserting some clients *********'
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Katya', 'Corris', '1973-06-28', 'kcorris0@slashdot.org', '1234', '0104 Waubesa Lane', 69640, 'Nicasio', '+51 755 872 2357');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Veronica', 'Castree', '2000-01-10', 'vcastree1@ox.ac.uk', '1234', '738 Clarendon Avenue', 64563, 'Cocieri', '+373 962 614 5220');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Buddie', 'Garz', '1989-02-01', 'bgarz2@wordpress.com', '1234', '49121 Jenna Court', 96014, 'Huaxijie', '+86 670 153 1182');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Shalom', 'Bacon', '1981-11-07', 'sbacon3@sina.com.cn', '1234', '92950 Dunning Plaza', 57136, 'Ia Kha', '+84 686 820 1502');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Vin', 'St. Pierre', '1996-07-15', 'vstpierre4@cdbaby.com', '1234', '93 Kingsford Crossing', 17684, 'Kajuru', '+234 818 577 7495');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Koralle', 'Dumpleton', '1978-11-18', 'kdumpleton5@redcross.org', '1234', '1359 School Terrace', 60920, 'Nueva Gorgona', '+507 246 467 4352');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Fanni', 'Tutchings', '1991-02-16', 'ftutchings6@wunderground.com', '1234', '81 Rigney Court', 60623, 'Houston', '+1 832 820 7581');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Britney', 'Paxforde', '1996-05-21', 'bpaxforde7@usa.gov', '1234', '86225 Montana Avenue', 78751, 'Terpinnya', '+380 705 282 2811');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Tasia', 'Freeland', '1983-05-28', 'tfreeland8@hostgator.com', '1234', '35199 Hansons Center', 46749, 'Jēkabpils', '+371 766 252 9704');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Renell', 'Dowdall', '1992-06-22', 'rdowdall9@smugmug.com', '1234', '62186 Hermina Parkway', 16350, 'Koška', '+385 930 339 3163');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Trixy', 'Lyford', '1984-01-04', 'tlyforda@gov.uk', '1234', '18846 Northport Circle', 45656, 'Jiangxiangzhen', '+86 437 572 1303');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Lari', 'Youhill', '1977-10-24', 'lyouhillb@de.vu', '1234', '44 Longview Pass', 56797, 'Jelah', '+387 507 213 0351');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Bride', 'Heard', '1993-06-26', 'bheardc@com.com', '1234', '844 Dayton Plaza', 96306, 'Currais Novos', '+55 999 157 2731');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Betteanne', 'De Souza', '1972-05-20', 'bdesouzad@adobe.com', '1234', '9401 Banding Plaza', 52697, 'Czerwieńsk', '+48 467 515 7556');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Oona', 'Denziloe', '1997-02-05', 'odenziloee@yellowbook.com', '1234', '329 Graceland Center', 93195, 'Shah Alam', '+60 388 968 3344');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Yolanda', 'Eddy', '1999-06-11', 'yeddyf@rakuten.co.jp', '1234', '51 Lunder Trail', 95064, 'Yishui', '+86 625 949 0614');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('June', 'Ervin', '1995-04-03', 'jerving@hud.gov', '1234', '33056 Ludington Way', 46161, 'Berezayka', '+7 276 154 6243');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Morgan', 'Fellis', '1993-11-04', 'mfellish@latimes.com', '1234', '4978 Cottonwood Court', 63214, 'Levallois-Perret', '+33 112 467 4787');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Vevay', 'Wrack', '1997-10-11', 'vwracki@senate.gov', '1234', '6586 Schmedeman Hill', 91481, 'Betong', '+66 745 928 2469');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Hewie', 'Robak', '1987-09-10', 'hrobakj@msu.edu', '1234', '72 Vera Junction', 95913, 'Shalakusha', '+7 698 970 1584');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Rodolph', 'Dunning', '1982-04-08', 'rdunningk@craigslist.org', '1234', '36322 Straubel Lane', 68297, 'Keelung', '+886 794 206 2042');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Tiphany', 'Morgan', '1991-12-17', 'tmorganl@studiopress.com', '1234', '99 Lakewood Point', 97304, 'Handaqi', '+86 229 958 4673');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Daune', 'Bonniface', '1993-03-23', 'dbonnifacem@marketwatch.com', '1234', '9728 Norway Maple Circle', 99992, 'Poděbrady', '+420 778 923 3077');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Olav', 'Wildgoose', '1999-03-28', 'owildgoosen@jimdo.com', '1234', '86 Aberg Street', 47006, 'Valle San Francisco', '+505 154 522 7020');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Gus', 'Oakhill', '1972-09-18', 'goakhillo@fastcompany.com', '1234', '158 Amoth Plaza', 53232, 'Zekou', '+86 443 442 2298');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Deana', 'Tozer', '1997-06-10', 'dtozerp@illinois.edu', '1234', '2 Rutledge Point', 78488, 'Jiancheng', '+86 435 967 2908');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Lurleen', 'Paulou', '1994-08-22', 'lpaulouq@hud.gov', '1234', '7 Bay Terrace', 91982, 'Combapata', '+51 336 687 3609');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Tanhya', 'Platfoot', '1991-10-27', 'tplatfootr@squidoo.com', '1234', '736 Village Green Hill', 50952, 'Marsabit', '+254 975 476 2454');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Eberhard', 'Edsell', '1978-05-06', 'eedsells@edublogs.org', '1234', '09552 Ridgeview Circle', 44746, 'Kaskinen', '+358 955 816 1176');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Forest', 'Trembley', '1999-07-28', 'ftrembleyt@fema.gov', '1234', '9 Sugar Road', 15377, 'Kohila', '+372 203 985 8944');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Kirsteni', 'Parffrey', '2001-11-02', 'kparffreyu@google.com', '1234', '640 Starling Court', 78746, 'Velas', '+351 231 747 3629');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Elbertine', 'Bromehed', '1976-07-01', 'ebromehedv@yellowpages.com', '1234', '38 Hallows Place', 96389, 'Doubrava', '+420 318 189 3728');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Jsandye', 'Kington', '1979-04-14', 'jkingtonw@ovh.net', '1234', '32862 Corscot Plaza', 88857, 'Calimete', '+53 873 118 7697');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Guthrey', 'Nehls', '1976-04-15', 'gnehlsx@addthis.com', '1234', '81 Pearson Lane', 45623, 'Thị Trấn Mường Lát', '+84 643 600 3120');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Joya', 'Lempel', '1992-06-18', 'jlempely@rambler.ru', '1234', '772 Northridge Plaza', 95580, 'Narawayong', '+62 905 174 7953');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Lilllie', 'Jekyll', '1997-09-25', 'ljekyllz@bloglovin.com', '1234', '23 Aberg Place', 28952, 'Cestas', '+33 302 254 3557');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Krishnah', 'Clewley', '1983-08-25', 'kclewley10@bloglines.com', '1234', '9 Caliangt Road', 29281, 'Tarłów', '+48 589 475 8059');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Bren', 'Pavey', '1980-11-11', 'bpavey11@hibu.com', '1234', '34 Fairfield Road', 57044, 'Cabanbanan', '+63 395 409 4217');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Bevin', 'Pounds', '1997-12-20', 'bpounds12@deliciousdays.com', '1234', '6 Grasskamp Drive', 59743, 'Cikou', '+86 591 649 9188');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Genevieve', 'Caseley', '1989-11-15', 'gcaseley13@harvard.edu', '1234', '2 Merrick Plaza', 57104, 'Puerto Bello', '+63 399 310 8985');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Zilvia', 'Jeffery', '1996-08-08', 'zjeffery14@fda.gov', '1234', '77 Thierer Crossing', 87325, 'Mainri', '+86 929 666 4892');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Beverie', 'Bigadike', '1982-04-09', 'bbigadike15@google.it', '1234', '06 Autumn Leaf Junction', 20265, 'Qila Abdullāh', '+92 519 204 8416');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Anselma', 'Boyet', '1973-04-10', 'aboyet16@miitbeian.gov.cn', '1234', '6 Green Ridge Alley', 41326, 'Vigo', '+34 866 800 0843');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Tiebout', 'Sirrell', '1981-04-14', 'tsirrell17@wufoo.com', '1234', '51091 Bunting Crossing', 38733, 'Keetmanshoop', '+264 717 427 8361');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Sylvester', 'Oxbury', '1977-01-27', 'soxbury18@dmoz.org', '1234', '68 Lindbergh Place', 69368, 'Fullerton', '+1 714 280 0082');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Corri', 'Silliman', '1986-05-30', 'csilliman19@freewebs.com', '1234', '6 Scoville Hill', 90359, 'Berdyans’k', '+380 187 156 4013');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Patience', 'Hamsson', '1984-10-19', 'phamsson1a@taobao.com', '1234', '44 Hovde Road', 28018, 'Ropice', '+420 128 662 1585');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Delmore', 'Heningam', '1971-09-05', 'dheningam1b@quantcast.com', '1234', '3 Mcbride Trail', 12350, 'Banjar Beratan', '+62 956 614 6351');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Thane', 'Camacke', '1983-02-20', 'tcamacke1c@about.me', '1234', '357 Scofield Crossing', 13630, 'Ho', '+233 938 369 9030');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Margie', 'Fussie', '1983-10-07', 'mfussie1d@epa.gov', '1234', '08 Morrow Lane', 16502, 'Clermont-Ferrand', '+33 250 623 5341');
\echo '********* Inserting some ads *********'
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Administrative Officer', 'Sensory problem w head', '136,41', 2, 5, '1980-02-18', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Software Engineer III', 'Fetal abnorm NOS-unspec', '3265,08', 9, 27, '1974-02-26', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Desktop Support Technician', 'React psychosis NEC/NOS', '1987,30', 14, 23, '1994-12-22', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Occupational Therapist', 'Gu infection-deliv w p/p', '649,27', 46, 21, '1975-05-24', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Nuclear Power Engineer', 'Spstc hmiplga domnt side', '2889,60', 37, 25, '1988-06-10', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Help Desk Operator', 'Hx-laryngeal malignancy', '4771,23', 18, 15, '1980-05-07', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Electrical Engineer', 'Prim TB complex-histo dx', '40,64', 9, 1, '1985-06-07', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Marketing Assistant', 'Fx humer, lat condyl-opn', '257,84', 30, 39, '1976-10-27', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Food Chemist', 'Aircrft acc NEC-occp NEC', '418,77', 47, 40, '1974-12-01', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Mechanical Systems Engineer', 'Infestation NOS', '4683,12', 16, 27, '1981-01-16', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Product Engineer', 'Tk off/land-unp aircrft', '2933,14', 48, 6, '1983-10-18', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Human Resources Assistant III', 'Thrombosis NEC-antepart', '2186,99', 5, 31, '1978-01-19', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Recruiting Manager', 'Benign neo trunk NOS', '3354,05', 2, 11, '1996-09-18', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Financial Analyst', 'Incor dilut infusn fluid', '2003,05', 45, 18, '1977-04-28', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Operator', 'Binocular vision dis NOS', '3198,06', 20, 40, '1983-04-30', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Teacher', 'Cong bowing leg NOS', '465,49', 38, 41, '1976-01-28', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Media Manager IV', 'Sprain lumbosacral', '3086,68', 45, 1, '1984-06-19', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Engineer IV', 'Power aircraft acc-milit', '984,71', 12, 49, '1975-01-01', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Systems Administrator III', 'Opn skl vlt fx/cereb lac', '2881,78', 27, 9, '1997-03-24', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Pharmacist', 'Ch DVT/embl low ext NOS', '3326,07', 16, 5, '1996-12-30', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Senior Developer', 'Neurohypophysis dis NEC', '961,35', 1, 2, '1986-08-23', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Safety Technician IV', 'Hx-oral/pharynx malg NEC', '4685,36', 47, 18, '1991-10-27', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('VP Product Management', 'Protein defic anemia', '159,63', 40, 13, '1987-06-03', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Compensation Analyst', 'Sciatic nerve lesion', '3345,63', 14, 27, '1977-08-03', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Research Nurse', 'Dis mineral metabol NEC', '853,65', 11, 22, '1975-11-05', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Office Assistant IV', 'NB intraven hem,grade iv', '3545,52', 22, 12, '1976-04-03', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Health Coach II', 'Hx-health hazards NEC', '4738,48', 1, 6, '1974-06-22', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Information Systems Manager', 'Cl skull fx NEC-mod coma', '3677,07', 3, 6, '1999-12-11', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Marketing Manager', 'Effects radiation NOS', '1482,30', 5, 4, '1989-09-24', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Junior Executive', 'Chalazion', '3243,88', 16, 12, '1990-04-26', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Executive Secretary', 'Anaph react d/t ot serum', '1505,94', 15, 44, '1974-05-31', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Senior Cost Accountant', 'Gc prostatitis (acute)', '3108,24', 12, 27, '1980-02-14', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Assistant Manager', 'Quadruplet preg-unspec', '2511,29', 13, 16, '1995-01-18', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Chief Design Engineer', 'Ca in situ NOS', '754,71', 38, 12, '2000-12-09', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Legal Assistant', 'Squam cell ca skin trunk', '1462,29', 34, 49, '1978-12-15', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Paralegal', 'Malign neopl thyroid', '3625,32', 19, 50, '1990-05-07', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Mechanical Systems Engineer', 'Ganglion NOS', '658,57', 13, 47, '1975-07-11', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Operator', 'Hot substance accid NOS', '702,68', 2, 18, '1977-02-01', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Financial Analyst', 'Carbuncle of leg', '4883,37', 6, 7, '1974-02-17', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Product Engineer', 'Late eff cert ext cause', '1736,70', 15, 38, '1971-02-16', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Media Manager II', 'Hang gliding', '2153,09', 34, 24, '1987-08-31', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Director of Sales', 'Neutropenia NOS', '3683,65', 7, 4, '1983-10-19', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Nuclear Power Engineer', 'Synovial cyst NOS', '3516,32', 48, 47, '1997-04-29', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Senior Editor', 'Fascioliasis', '1686,17', 20, 41, '1993-12-20', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Cost Accountant', 'Rh isoimmunizat-deliver', '3524,28', 30, 11, '1984-07-07', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('VP Quality Control', 'Compl lab/deliv NOS-unsp', '271,78', 23, 16, '1995-11-15', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Accountant IV', 'Erosion NOS', '4695,19', 46, 19, '1976-12-02', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Database Administrator II', 'Acc poison-bromine cmpnd', '3878,65', 13, 21, '1973-02-03', true);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Administrative Officer', 'Ob pelvic hematoma-unsp', '3439,33', 17, 19, '1993-11-27', false);
INSERT INTO ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) VALUES ('Chemical Engineer', 'Longitud defic phalanges', '1326,48', 16, 1, '1976-02-28', true);