\echo '******** Set The Database ********'

\c db_psi

\echo '********* Inserting some data *********'

\echo '********* Restarting all sequences *********'
ALTER SEQUENCE adimages_id_seq RESTART;
ALTER SEQUENCE ads_id_seq RESTART;
ALTER SEQUENCE clients_id_seq RESTART;
ALTER SEQUENCE categories_id_seq RESTART;
ALTER SEQUENCE messages_id_seq RESTART;

\echo '********* Inserting some categories *********'
INSERT INTO categories (name) VALUES ('informatique');
INSERT INTO categories (name) VALUES ('Consoles & Jeux vidéo');
INSERT INTO categories (name) VALUES ('Image & Son');
INSERT INTO categories (name) VALUES ('Téléphonie');
INSERT INTO categories (name) VALUES ('Ameublement');
INSERT INTO categories (name) VALUES ('Électroménager');
INSERT INTO categories (name) VALUES ('Arts de la table');
INSERT INTO categories (name) VALUES ('Décoration');
INSERT INTO categories (name) VALUES ('Linge de maison');
INSERT INTO categories (name) VALUES ('Bricolage');
INSERT INTO categories (name) VALUES ('Jardinage');
INSERT INTO categories (name) VALUES ('Vêtements');
INSERT INTO categories (name) VALUES ('Chaussures');
INSERT INTO categories (name) VALUES ('Accessoires & Bagagerie');
INSERT INTO categories (name) VALUES ('Montres & Bijoux');
INSERT INTO categories (name) VALUES ('Équipement bébé');
INSERT INTO categories (name) VALUES ('Vêtements bébé');
INSERT INTO categories (name) VALUES ('Luxe et Tendance');
INSERT INTO categories (name) VALUES ('Locations & Gîtes');
INSERT INTO categories (name) VALUES ('Chambres de hôtes');
INSERT INTO categories (name) VALUES ('Campings');
INSERT INTO categories (name) VALUES ('Hôtels');
INSERT INTO categories (name) VALUES ('Hébergements insolites');
INSERT INTO categories (name) VALUES ('Ventes privées vacances');
INSERT INTO categories (name) VALUES ('Voitures');
INSERT INTO categories (name) VALUES ('Motos');
INSERT INTO categories (name) VALUES ('Caravaning');
INSERT INTO categories (name) VALUES ('Utilitaires');
INSERT INTO categories (name) VALUES ('Camions');
INSERT INTO categories (name) VALUES ('Nautisme');
INSERT INTO categories (name) VALUES ('Équipement auto');
INSERT INTO categories (name) VALUES ('Équipement moto');
INSERT INTO categories (name) VALUES ('Équipement caravaning');
INSERT INTO categories (name) VALUES ('Équipement nautisme');
INSERT INTO categories (name) VALUES ('Ventes immobilières');
INSERT INTO categories (name) VALUES ('Immobilier Neuf');
INSERT INTO categories (name) VALUES ('Locations');
INSERT INTO categories (name) VALUES ('Colocations');
INSERT INTO categories (name) VALUES ('Bureaux & Commerces');
INSERT INTO categories (name) VALUES ('Animaux');
INSERT INTO categories (name) VALUES ('DVD - Films');
INSERT INTO categories (name) VALUES ('CD - Musique');
INSERT INTO categories (name) VALUES ('Livres');
INSERT INTO categories (name) VALUES ('Vélos');
INSERT INTO categories (name) VALUES ('Sports & Hobbies');
INSERT INTO categories (name) VALUES ('Instruments de musique');
INSERT INTO categories (name) VALUES ('Collection');
INSERT INTO categories (name) VALUES ('Jeux & Jouets');
INSERT INTO categories (name) VALUES ('Vins & Gastronomie');
\echo '********* Inserting some clients *********'
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Katya', 'Corris', '1973-06-28', 'userone@gmail.com', '1234', '0104 Waubesa Lane', 69640, 'Nicasio', '+51 755 872 2357');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Veronica', 'Castree', '2000-01-10', 'usertwo@gmail.com', '1234', '738 Clarendon Avenue', 64563, 'Cocieri', '+373 962 614 5220');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Buddie', 'Garz', '1989-02-01', 'userthree@gmail.com', '1234', '49121 Jenna Court', 96014, 'Huaxijie', '+86 670 153 1182');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Shalom', 'Bacon', '1981-11-07', 'userfour@gmail.com', '1234', '92950 Dunning Plaza', 57136, 'Ia Kha', '+84 686 820 1502');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Vin', 'St. Pierre', '1996-07-15', 'userfive@gmail.com', '1234', '93 Kingsford Crossing', 17684, 'Kajuru', '+234 818 577 7495');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Koralle', 'Dumpleton', '1978-11-18', 'usersix@gmail.com', '1234', '1359 School Terrace', 60920, 'Nueva Gorgona', '+507 246 467 4352');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Fanni', 'Tutchings', '1991-02-16', 'userseven@gmail.com', '1234', '81 Rigney Court', 60623, 'Houston', '+1 832 820 7581');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Britney', 'Paxforde', '1996-05-21', 'usereight@gmail.com', '1234', '86225 Montana Avenue', 78751, 'Terpinnya', '+380 705 282 2811');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Tasia', 'Freeland', '1983-05-28', 'usernine@gmail.com', '1234', '35199 Hansons Center', 46749, 'Jēkabpils', '+371 766 252 9704');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Renell', 'Dowdall', '1992-06-22', 'userten@gmail.com', '1234', '62186 Hermina Parkway', 16350, 'Koška', '+385 930 339 3163');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Trixy', 'Lyford', '1984-01-04', 'usereleven@gmail.com', '1234', '18846 Northport Circle', 45656, 'Jiangxiangzhen', '+86 437 572 1303');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Lari', 'Youhill', '1977-10-24', 'usertwelve@gmail.com', '1234', '44 Longview Pass', 56797, 'Jelah', '+387 507 213 0351');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Bride', 'Heard', '1993-06-26', 'userthirteen@gmail.com', '1234', '844 Dayton Plaza', 96306, 'Currais Novos', '+55 999 157 2731');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Betteanne', 'De Souza', '1972-05-20', 'userfourteeg@gmail.com', '1234', '9401 Banding Plaza', 52697, 'Czerwieńsk', '+48 467 515 7556');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Oona', 'Denziloe', '1997-02-05', 'userfifteen@gmail.com', '1234', '329 Graceland Center', 93195, 'Shah Alam', '+60 388 968 3344');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Yolanda', 'Eddy', '1999-06-11', 'yeddyf@rakuten.co.jp', '1234', '51 Lunder Trail', 95064, 'Yishui', '+86 625 949 0614');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('June', 'Ervin', '1995-04-03', 'jerving@hud.gov', '1234', '33056 Ludington Way', 46161, 'Berezayka', '+7 276 154 6243');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Morgan', 'Fellis', '1993-11-04', 'mfellish@latimes.com', '1234', '4978 Cottonwood Court', 63214, 'Levallois-Perret', '+33 112 467 4787');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Vevay', 'Wrack', '1997-10-11', 'vwracki@senate.gov', '1234', '6586 Schmedeman Hill', 91481, 'Betong', '+66 745 928 2469');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Hewie', 'Robak', '1987-09-10', 'hrobakj@msu.edu', '1234', '72 Vera Junction', 95913, 'Shalakusha', '+7 698 970 1584');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Rodolph', 'Dunning', '1982-04-08', 'rdunningk@craigslist.org', '1234', '36322 Straubel Lane', 68297, 'Keelung', '+886 794 206 2042');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Tiphany', 'Morgan', '1991-12-17', 'tmorganl@studiopress.com', '1234', '99 Lakewood Point', 97304, 'Handaqi', '+86 229 958 4673');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Daune', 'Bonniface', '1993-03-23', 'dbonnifacem@marketwatch.com', '1234', '9728 Norway Maple Circle', 99992, 'Poděbrady', '+420 778 923 3077');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Olav', 'Wildgoose', '1999-03-28', 'owildgoosen@jimdo.com', '1234', '86 Aberg Street', 47006, 'Valle San Francisco', '+505 154 522 7020');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Gus', 'Oakhill', '1972-09-18', 'goakhillo@fastcompany.com', '1234', '158 Amoth Plaza', 53232, 'Zekou', '+86 443 442 2298');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Deana', 'Tozer', '1997-06-10', 'dtozerp@illinois.edu', '1234', '2 Rutledge Point', 78488, 'Jiancheng', '+86 435 967 2908');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Lurleen', 'Paulou', '1994-08-22', 'lpaulouq@hud.gov', '1234', '7 Bay Terrace', 91982, 'Combapata', '+51 336 687 3609');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Tanhya', 'Platfoot', '1991-10-27', 'tplatfootr@squidoo.com', '1234', '736 Village Green Hill', 50952, 'Marsabit', '+254 975 476 2454');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Eberhard', 'Edsell', '1978-05-06', 'eedsells@edublogs.org', '1234', '09552 Ridgeview Circle', 44746, 'Kaskinen', '+358 955 816 1176');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Forest', 'Trembley', '1999-07-28', 'ftrembleyt@fema.gov', '1234', '9 Sugar Road', 15377, 'Kohila', '+372 203 985 8944');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Kirsteni', 'Parffrey', '2001-11-02', 'kparffreyu@google.com', '1234', '640 Starling Court', 78746, 'Velas', '+351 231 747 3629');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Elbertine', 'Bromehed', '1976-07-01', 'ebromehedv@yellowpages.com', '1234', '38 Hallows Place', 96389, 'Doubrava', '+420 318 189 3728');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Jsandye', 'Kington', '1979-04-14', 'jkingtonw@ovh.net', '1234', '32862 Corscot Plaza', 88857, 'Calimete', '+53 873 118 7697');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Guthrey', 'Nehls', '1976-04-15', 'gnehlsx@addthis.com', '1234', '81 Pearson Lane', 45623, 'Thị Trấn Mường Lát', '+84 643 600 3120');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Joya', 'Lempel', '1992-06-18', 'jlempely@rambler.ru', '1234', '772 Northridge Plaza', 95580, 'Narawayong', '+62 905 174 7953');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Lilllie', 'Jekyll', '1997-09-25', 'ljekyllz@bloglovin.com', '1234', '23 Aberg Place', 28952, 'Cestas', '+33 302 254 3557');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Krishnah', 'Clewley', '1983-08-25', 'kclewley10@bloglines.com', '1234', '9 Caliangt Road', 29281, 'Tarłów', '+48 589 475 8059');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Bren', 'Pavey', '1980-11-11', 'bpavey11@hibu.com', '1234', '34 Fairfield Road', 57044, 'Cabanbanan', '+63 395 409 4217');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Bevin', 'Pounds', '1997-12-20', 'bpounds12@deliciousdays.com', '1234', '6 Grasskamp Drive', 59743, 'Cikou', '+86 591 649 9188');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Genevieve', 'Caseley', '1989-11-15', 'gcaseley13@harvard.edu', '1234', '2 Merrick Plaza', 57104, 'Puerto Bello', '+63 399 310 8985');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Zilvia', 'Jeffery', '1996-08-08', 'zjeffery14@fda.gov', '1234', '77 Thierer Crossing', 87325, 'Mainri', '+86 929 666 4892');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Beverie', 'Bigadike', '1982-04-09', 'bbigadike15@google.it', '1234', '06 Autumn Leaf Junction', 20265, 'Qila Abdullāh', '+92 519 204 8416');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Anselma', 'Boyet', '1973-04-10', 'aboyet16@miitbeian.gov.cn', '1234', '6 Green Ridge Alley', 41326, 'Vigo', '+34 866 800 0843');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Tiebout', 'Sirrell', '1981-04-14', 'tsirrell17@wufoo.com', '1234', '51091 Bunting Crossing', 38733, 'Keetmanshoop', '+264 717 427 8361');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Sylvester', 'Oxbury', '1977-01-27', 'soxbury18@dmoz.org', '1234', '68 Lindbergh Place', 69368, 'Fullerton', '+1 714 280 0082');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Corri', 'Silliman', '1986-05-30', 'csilliman19@freewebs.com', '1234', '6 Scoville Hill', 90359, 'Berdyans’k', '+380 187 156 4013');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Patience', 'Hamsson', '1984-10-19', 'phamsson1a@taobao.com', '1234', '44 Hovde Road', 28018, 'Ropice', '+420 128 662 1585');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Delmore', 'Heningam', '1971-09-05', 'dheningam1b@quantcast.com', '1234', '3 Mcbride Trail', 12350, 'Banjar Beratan', '+62 956 614 6351');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Thane', 'Camacke', '1983-02-20', 'tcamacke1c@about.me', '1234', '357 Scofield Crossing', 13630, 'Ho', '+233 938 369 9030');
INSERT INTO clients (first_name, last_name, birthdate, email, password, address, postal_code, city, phone_number) VALUES ('Margie', 'Fussie', '1983-10-07', 'mfussie1d@epa.gov', '1234', '08 Morrow Lane', 16502, 'Clermont-Ferrand', '+33 250 623 5341');
\echo '********* Inserting some ads *********'
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Stranger Than Paradise', 'Benign carcinoid jejunum', 196.8, 9, 41, '2020-01-31', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('The Plague of the Zombies', 'Part edentulism,class I', 183.57, 30, 47, '2020-04-14', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('My Father and My Son (Babam ve oglum)', 'Radioact isotope exposur', 469.16, 29, 19, '2020-03-24', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Zorro', 'Isolated/spec phobia NEC', 441.6, 10, 21, '2020-05-08', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Crimi Clowns: De Movie', 'Fx up tibia w fibula-cl', 441.38, 22, 33, '2019-12-18', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('The First Men in the Moon', 'Famly dsrpt-chld custody', 123.31, 12, 46, '2019-12-15', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Airbag', 'Foreign body in vitreous', 412.96, 7, 6, '2020-01-01', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Like Crazy', 'Torus fracture of fibula', 497.14, 17, 36, '2020-08-02', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Lord of the Flies', 'Birth trauma NOS', 429.43, 48, 22, '2020-07-10', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Doctor Who: The Time of the Doctor', 'Opn skl w oth fx/hem NEC', 226.41, 19, 44, '2020-02-21', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Trou, Le (Hole, The) (Night Watch, The)', 'Palindrom rheum-l/leg', 137.73, 46, 46, '2020-04-25', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Dutch', 'Diarrhea of infect orig', 206.49, 42, 40, '2020-10-31', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Transformers: Revenge of the Fallen', 'Monoarthritis NOS-up/arm', 404.95, 35, 48, '2020-05-24', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Police Academy 4: Citizens on Patrol', 'Thrombocytopenia NOS', 166.8, 20, 32, '2020-10-24', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Red Angel (Akai tenshi)', 'Malig neo exocervix', 416.4, 38, 41, '2020-06-21', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Killer Inside Me, The', 'Autoimmune hepatitis', 151.7, 9, 11, '2020-05-03', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Victor Sjöström: Ett porträtt', 'Acc poison-polishes', 384.72, 17, 2, '2020-04-30', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Simple Men', 'Listeriosis', 475.41, 23, 11, '2020-04-17', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Dudley Do-Right', '80-89% bdy brn/30-39% 3d', 189.68, 12, 32, '2020-02-07', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Curse of the Jade Scorpion, The', 'Meconium obstruction', 473.84, 26, 3, '2020-03-21', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Direct from Brooklyn', 'Incontnce wo sensr aware', 415.25, 43, 14, '2020-06-22', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Car 54, Where Are You?', 'Dacryocystitis NOS', 487.7, 31, 35, '2020-05-02', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Rebirth', 'Probl w special func NOS', 458.64, 16, 42, '2020-11-03', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Under the Stars (Bajo las estrellas)', 'Exfl d/t eryth 60-69 bdy', 314.61, 42, 43, '2020-09-19', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Wild Bees, The (Divoké vcely)', 'Portal hypertension', 438.92, 5, 36, '2020-06-30', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('The Noble Family', 'Acc-power hand tool NEC', 157.78, 39, 40, '2020-03-29', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Naked Spur, The', 'Cl skul vlt fx-deep coma', 477.52, 3, 44, '2020-02-27', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Sylvia Scarlett', 'Pap smear cervix w HGSIL', 100.03, 22, 8, '2020-10-23', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Nashville', 'Polycyst kid-autosom rec', 135.26, 14, 29, '2020-09-20', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Running Man, The', 'TB pneumothorx-exam unkn', 415.78, 18, 48, '2020-08-03', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Quatsch und die Nasenbärbande', 'Cryst arthrop NOS-mult', 264.17, 17, 22, '2020-04-03', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Road to Nowhere', 'Prolonged preg-del', 363.03, 48, 19, '2020-07-03', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Fanatics (Kulman pojat)', 'Genetc sus mult endo neo', 293.52, 12, 46, '2020-05-02', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Sun Also Rises, The (Tai yang zhao chang sheng qi)', 'Fibromatoses NEC', 367.29, 11, 14, '2020-06-15', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Pirates of the Caribbean: At World''s End', 'Vasc comp renal artery', 111.08, 37, 10, '2019-12-04', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Teen Wolf Too', 'Premature beats NOS', 182.78, 40, 25, '2020-07-15', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Fire of Conscience (For lung)', 'Optic nerve disorder NOS', 136.72, 33, 22, '2020-01-12', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Grand Tour: Disaster in Time (Timescape)', 'Nodular lymphoma thorax', 265.52, 43, 35, '2019-11-19', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Captain America: The Winter Soldier', 'Mal neo uterine isthmus', 398.8, 15, 6, '2020-01-31', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Day of the Dead 2: Contagium', 'Acq pelvic deformity', 187.59, 31, 3, '2020-10-27', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Star 80', 'Lymphosarcoma mult', 194.74, 13, 29, '2020-02-04', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Lord of the Flies', 'Intes infec rotavirus', 234.21, 46, 48, '2020-11-03', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('7 Days in Havana', 'Oth tissue graft malfunc', 217.72, 18, 36, '2020-04-26', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Wings of Courage', 'Lt-date w/mal 1500-1749g', 367.77, 17, 20, '2020-06-19', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Austin High', 'Mal neo aryepiglott fold', 241.3, 45, 12, '2020-10-03', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Death In Love', 'Hpt B acte coma wo dlta', 413.79, 44, 36, '2020-08-11', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Terror''s Advocate (Avocat de la terreur, L'')', 'Nontrauma comp syn-abd', 472.26, 18, 31, '2019-11-20', false);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Myth of the American Sleepover, The', 'Reticulosarcoma thorax', 160.27, 7, 9, '2019-12-10', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Wrestling for Jesus: The Tale of T-Money', 'Hx surgery to organs NEC', 147.52, 10, 17, '2019-11-09', true);
insert into ads (title, description, price, id_cat, posted_by, posting_date, is_reserved) values ('Sorority Row', 'Endocard cushion def NOS', 434.84, 17, 5, '2020-09-25', true);